import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import '../models/medical_profile.dart';

class AiSummaryService {
  static const String _geminiApiKey = String.fromEnvironment('GEMINI_API_KEY');
  static const String _geminiUrl =
      'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent';

  /// Generates AI emergency summary. Uses Gemini API if an API key is supplied,
  /// otherwise falls back seamlessly to rule-based AI clinical summary.
  static Future<String> generateSummaryAsync(MedicalProfile profile, {String? apiKey}) async {
    final key = apiKey ?? _geminiApiKey;
    if (key.isNotEmpty) {
      try {
        final geminiSummary = await _fetchGeminiSummary(profile, key);
        if (geminiSummary != null && geminiSummary.isNotEmpty) {
          return geminiSummary;
        }
      } catch (e) {
        debugPrint('Gemini API call error: $e. Falling back to local AI rules.');
      }
    }

    return generateSummary(profile);
  }

  /// Calls Gemini 1.5 Flash API securely.
  static Future<String?> _fetchGeminiSummary(MedicalProfile profile, String apiKey) async {
    final prompt = '''
You are a medical emergency AI assistant.
Analyze the following patient medical information and generate a short, clear emergency summary for first responders.
Highlight critical information such as allergies, diseases, and medications. Do NOT invent any medical facts not listed below.

Patient Info:
- Name: ${profile.fullName}
- Age: ${profile.age}
- Gender: ${profile.gender}
- Blood Group: ${profile.bloodGroup}
- Allergies: ${profile.allergies.join(', ')}
- Diseases/Conditions: ${profile.diseases.join(', ')}
- Current Medications: ${profile.medications.join(', ')}
- Organ Donor: ${profile.isOrganDonor ? 'Yes' : 'No'}
- Medical Notes: ${profile.medicalNotes}
- Emergency Contact: ${profile.emergencyContactName} (${profile.relationship}) - ${profile.emergencyPhone}
- QR Emergency ID: ${profile.qrId}

Format with clear headers and emergency symbols. Keep it under 250 words.
''';

    final uri = Uri.parse('$_geminiUrl?key=$apiKey');
    final response = await http.post(
      uri,
      headers: {'Content-Type': 'application/json'},
      body: jsonEncode({
        'contents': [
          {
            'parts': [
              {'text': prompt}
            ]
          }
        ]
      }),
    );

    if (response.statusCode == 200) {
      final json = jsonDecode(response.body);
      final text = json['candidates']?[0]?['content']?['parts']?[0]?['text'];
      if (text is String && text.trim().isNotEmpty) {
        return text.trim();
      }
    } else {
      debugPrint('Gemini API status ${response.statusCode}: ${response.body}');
    }
    return null;
  }

  /// Deterministic clinical summary generator (Offline-First Rule-Based AI)
  static String generateSummary(MedicalProfile profile) {
    final buffer = StringBuffer();

    buffer.writeln('🆘 EMERGENCY MEDICAL SUMMARY');
    buffer.writeln('Generated by AI Life Vault\n');

    // Identity
    buffer.writeln('👤 PATIENT: ${profile.fullName}, ${profile.age} yrs, ${profile.gender}');
    buffer.writeln('🩸 BLOOD GROUP: ${profile.bloodGroup}');

    // BMI
    if (profile.bmi > 0) {
      buffer.writeln('⚖️ BMI: ${profile.bmi.toStringAsFixed(1)} (${profile.bmiCategory})');
    }

    buffer.writeln('');

    // Critical Allergies - HIGHEST PRIORITY
    if (profile.allergies.isNotEmpty) {
      buffer.writeln('⚠️ CRITICAL ALLERGIES:');
      for (final a in profile.allergies) {
        buffer.writeln('  • $a');
      }
      buffer.writeln('  ⛔ DO NOT ADMINISTER ALLERGENS ABOVE\n');
    } else {
      buffer.writeln('✅ No Known Allergies\n');
    }

    // Existing Diseases
    if (profile.diseases.isNotEmpty) {
      buffer.writeln('🏥 EXISTING CONDITIONS:');
      for (final d in profile.diseases) {
        buffer.writeln('  • $d');
      }
      buffer.writeln('');
    }

    // Current Medications
    if (profile.medications.isNotEmpty) {
      buffer.writeln('💊 CURRENT MEDICATIONS:');
      for (final m in profile.medications) {
        buffer.writeln('  • $m');
      }
      buffer.writeln('  ℹ️ Check for drug interactions\n');
    }

    // Organ Donor
    if (profile.isOrganDonor) {
      buffer.writeln('💚 ORGAN DONOR: YES — Please follow protocols\n');
    }

    // Medical Notes
    if (profile.medicalNotes.isNotEmpty) {
      buffer.writeln('📋 ADDITIONAL NOTES:');
      buffer.writeln('  ${profile.medicalNotes}\n');
    }

    // Emergency Contact
    buffer.writeln('📞 EMERGENCY CONTACT:');
    buffer.writeln('  ${profile.emergencyContactName} (${profile.relationship})');
    buffer.writeln('  📱 ${profile.emergencyPhone}');
    buffer.writeln('');

    // AI Risk Assessment
    buffer.writeln('🤖 AI RISK FLAGS:');
    final risks = _assessRisks(profile);
    if (risks.isEmpty) {
      buffer.writeln('  ✅ No critical risk flags detected');
    } else {
      for (final r in risks) {
        buffer.writeln('  🔴 $r');
      }
    }

    buffer.writeln('\n─────────────────────────────');
    buffer.writeln('Emergency ID: ${profile.qrId}');
    buffer.writeln('AI Life Vault | Offline Medical ID');

    return buffer.toString();
  }

  static List<String> _assessRisks(MedicalProfile profile) {
    final risks = <String>[];
    final diseases = profile.diseases.map<String>((e) => e.toString().toLowerCase()).toList();
    final meds = profile.medications.map<String>((e) => e.toString().toLowerCase()).toList();
    final allergies = profile.allergies.map<String>((e) => e.toString().toLowerCase()).toList();

    // Diabetes risk
    if (diseases.any((String d) => d.contains('diabet'))) {
      risks.add('Diabetic patient — check blood sugar');
      if (meds.any((String m) => m.contains('insulin'))) {
        risks.add('Insulin dependent — risk of hypoglycemia');
      }
    }

    // Heart conditions
    if (diseases.any((String d) => d.contains('heart') || d.contains('cardiac') || d.contains('hypertension'))) {
      risks.add('Cardiovascular condition — monitor vitals');
    }

    // Blood pressure
    if (diseases.any((String d) => d.contains('pressure') || d.contains('hypertension'))) {
      risks.add('Hypertension — avoid stimulants');
    }

    // Epilepsy
    if (diseases.any((String d) => d.contains('epileps') || d.contains('seizure'))) {
      risks.add('Epilepsy — seizure precautions required');
    }

    // Asthma
    if (diseases.any((String d) => d.contains('asthma') || d.contains('respiratory'))) {
      risks.add('Respiratory condition — avoid triggers');
    }

    // Penicillin allergy
    if (allergies.any((String a) => a.contains('penicillin'))) {
      risks.add('PENICILLIN ALLERGY — avoid beta-lactams');
    }

    // NSAIDs allergy
    if (allergies.any((String a) => a.contains('aspirin') || a.contains('nsaid') || a.contains('ibuprofen'))) {
      risks.add('NSAID/Aspirin allergy — avoid COX inhibitors');
    }

    // Organ donor
    if (profile.isOrganDonor) {
      risks.add('Registered organ donor — follow protocols');
    }

    // Blood thinners
    if (meds.any((String m) => m.contains('warfarin') || m.contains('aspirin') || m.contains('heparin') || m.contains('blood thinner'))) {
      risks.add('Blood thinners — increased bleeding risk');
    }

    // Kidney disease
    if (diseases.any((String d) => d.contains('kidney') || d.contains('renal'))) {
      risks.add('Renal condition — adjust medication dosage');
    }

    // Pregnancy
    if (diseases.any((String d) => d.contains('pregnan'))) {
      risks.add('Pregnancy — avoid teratogenic drugs');
    }

    // BMI extremes
    if (profile.bmi > 0) {
      if (profile.bmi < 16) risks.add('Severely underweight — nutritional risk');
      if (profile.bmi > 35) risks.add('Severe obesity — anaesthesia risk');
    }

    return risks;
  }

  static String generateShortSummary(MedicalProfile profile) {
    final parts = <String>[];
    parts.add('${profile.fullName} | ${profile.bloodGroup} | ${profile.age}yr ${profile.gender}');
    if (profile.allergies.isNotEmpty) {
      parts.add('⚠️ Allergies: ${profile.allergies.take(3).join(', ')}');
    }
    if (profile.diseases.isNotEmpty) {
      parts.add('🏥 Conditions: ${profile.diseases.take(2).join(', ')}');
    }
    if (profile.medications.isNotEmpty) {
      parts.add('💊 Meds: ${profile.medications.take(2).join(', ')}');
    }
    parts.add('📞 Emergency: ${profile.emergencyPhone}');
    return parts.join('\n');
  }
}
